apiVersion: v2
name: kuadrant-console-demo
description: Sample Gateways, HTTPRoutes, policies and APIProducts for Kuadrant Console demos (backed by mock-apis-3scale)
type: application
version: 0.1.0
appVersion: "1.0.0"
