apiVersion: v2
appVersion: 1.0.0
description: Financial Risk Evaluation AI Application Demo
home: https://everything-is-code.gitlab.io/neuralbank-stack/
icon: https://everything-is-code.gitlab.io/neuralbank-stack/neuralbank.svg
keywords:
- neuralbank
- banking
- microservices
- helm
maintainers:
- email: cestay@redhat.com
  name: Carlos Estay
- email: mapizarr@redhat.com
  name: Maximiliano Pizarro
name: neuralbank-stack
sources:
- https://gitlab.com/Everything-is-Code/neuralbank-stack
type: application
version: 0.1.0
